name: CI
  on: 
    push:
      branches: ['main', 'master']  

    pull_request:
      branches: ['main', 'master']

    env: 
      REGISTRY: 'cr.selcloud.ru/docker-vue/'
      IMAGE_NAME: 'docker-vue'
      CONTAINER_NAME: 'docker-vue-container'

    jobs: ''
      image-build-and-push:
      runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
      uses: actions/checkout@v3

      - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and push Docker image
      run: |
        TAG_NAME=${{ github.sha | head -c7 }}
        docker buildx create --use
        docker buildx build --no cache --push --platform linux/amd64 --tag REGISTRY/$IMAGE_NAME:$TAG_NAME .

deploy-image:
  runs-on: ubuntu-latest
  needs: image-build-and-push

  steps:
    -name: Deploy to Selectel Cloud via SSH action
    uses: selectel/ssh-action@v0.1.0
    with: 
      host: ${{ secrets.SERVER_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      envs: IMAGE-NAME, REGISTRTY, GITHUB_SHA, CONTAINER_NAME
      script: |
        TAG_NAME=${{ GITHUB.SHA | head -c7 }}
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
        docker stop $CONTAINER_NAME
        docker rm $CONTAINER_NAME
        docker run -d -p 80:1323 name $CONTAINER_NAME -t REGISTRTY/$IMAGE_NAME:$TAG_NAME